<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field;

class PriceTable extends Field
{
    protected $view = 'admin.price_table';

    public function render()
    {
        $name = $this->formatName($this->column);

        $count = count($this->value ?? []);

        $this->script = <<<JS
(function($) {
    var count = parseInt('$count');
    $("#pt-{$name}-addItem").on('click',function() {
        $.get('/admin/api/price_table_tr/$name/'+(count++),function(html) {
            $("#pt-{$name}-tbody").append(html);
            $(".pt-checkbox").iCheck({
              checkboxClass: 'icheckbox_minimal-blue',
              radioClass   : 'iradio_minimal-blue'
            });
        })
    });
    $(document).ready(function() {
        $(".pt-checkbox").iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        });
    });
    $(document).on();
})(jQuery);
JS;

        return parent::render(); // TODO: Change the autogenerated stub
    }
}
