<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field;

class PriceTable extends Field
{
    protected $view = 'admin.price_table';

    public function render()
    {
        $name = $this->formatName($this->column);

        $count = count($this->value??[]);

        $tr_tpl = <<<HTML
<tr>
    <td><input type="text" name="{$name}[new][name]" class="form-control"></td>
    <td>
        <input type="text" name="{$name}[new][period]" class="form-control"
            style="width: calc(100% - 65px);display: inline-block;">
        <select name="{$name}[new][period_unit]" class="form-control" style="width: 60px;display: inline-block;">
            <option value="day">天</option>
            <option value="month">月</option>
            <option value="year">年</option>
        </select>
    </td>
    <td><input type="text" name="{$name}[new][price]" class="form-control"></td>
    <td><input type="text" name="{$name}[new][remark]" class="form-control"></td>
    <td>
        <label class="checkbox-inline">
            <input type="checkbox" name="{$name}[new][enable]" class="pt-checkbox" />
        </label>
    </td>
    <td>
        <label class="checkbox-inline">
            <input type="checkbox" name="{$name}[new][auto_activate]" class="pt-checkbox" />
        </label>
    </td>
    <td>
        <label class="checkbox-inline">
            <input type="checkbox" name="{$name}[new][allow_renew]" class="pt-checkbox" />
        </label>
    </td>
</tr>
HTML;
        $tr_tpl = str_replace("\n","",$tr_tpl);

        $this->script = <<<JS
(function($) {
    var count = parseInt('$count');
    var tpl = '{$tr_tpl}';
    $("#pt-{$name}-addItem").on('click',function() {
        $("#pt-{$name}-tbody").append(tpl.replace(/new/g, String(count++)));
        $(".pt-checkbox").iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        });
    });
    $(document).ready(function() {
        $(".pt-checkbox").iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        });
    })
})(jQuery);
JS;


        return parent::render(); // TODO: Change the autogenerated stub
    }
}
