<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field;

class PriceTable extends Field
{
    protected $view = 'admin.price_table';

    public function render()
    {
        $name = $this->formatName($this->column);

        $count = count($this->value??[]);

        $tr_tpl = str_replace("\n","",view('admin.price_table_tr', ['name'=>$name,'index'=>'new']));

        $this->script = <<<JS
(function($) {
    var count = parseInt('$count');
    var tpl = '{$tr_tpl}';
    $("#pt-{$name}-addItem").on('click',function() {
        $("#pt-{$name}-tbody").append(tpl.replace(/new/g, String(count++)));
        $(".pt-checkbox").iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        });
    });
    $(document).ready(function() {
        $(".pt-checkbox").iCheck({
          checkboxClass: 'icheckbox_minimal-blue',
          radioClass   : 'iradio_minimal-blue'
        });
    });
})(jQuery);
JS;

        return parent::render(); // TODO: Change the autogenerated stub
    }
}
